version: '3.3'
services:

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - mysql-todos-db:/var/lib/mysql

  api-service:
    container_name: todos-api
    image: todos-api
    restart: always
    build: .
    environment:
      - ACCESS_ORIGIN=*
      - MYSQL_URL=user:password@tcp(mysql:3306)/db
      - JWT_SECRET=abosszz
      - PORT=8080
    networks:
      - backend
    ports:
      - "8080:8080"

volumes:
  mysql-todos-db:

networks:
  backend:
    driver: bridge