CREATE TABLE IF NOT EXISTS users (
    id       VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS todos (
    id       VARCHAR(255) PRIMARY KEY,
    title    VARCHAR(255) NOT NULL,
    complete BOOL         NOT NULL,
    username VARCHAR(255) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)